config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'kids#register'
  get '/signup', to: 'kids#register', as: 'register'
  post 'confirm', to: 'kids#confirm', as: 'confirm'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kid.rb
class Kid < ApplicationRecord
  belongs_to :group, optional: true
  
  scope :sort_by_last_name, -> { order( last_name: :asc ) }
  
  validates :first_name, :last_name, presence: true

  validates :birthdate, presence: true

  validates :gender, presence: true
  
  validates :address, :city, :zipcode, presence: true
  validates :state, presence: true
  validates :parent_name, presence: true
  
  VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :parent_email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }

  #TODO: we will need to make sure this is a valid phone number
  validates :parent_phone, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  helper ApplicationHelper
  
  #These methods are for working with kids from the registration perspective
  def register
    #Call render the fancy registration form
    @kid = Kid.new
    render layout: "public"
  end
  
  def confirm
    @kid = Kid.create(kid_params)
    if @kid.save
      render layout: "public"
    else
      flash.now[:warning] = "something went wrong"
      render 'register'
    end
  end
  private
  
  def kid_params
    params.require(:kid).permit(:first_name,
                                :last_name,
                                :birthdate,
                                :last_grade_id,
                                :gender,
                                :address,
                                :city,
                                :state,
                                :zipcode,
                                :parent_name,
                                :parent_email,
                                :parent_phone,
                                :church_member,
                                :invited_by,
                                :tshirt_size_id,
                                :allergies,
                                :allergies_notes,
                                :medical_issues,
                                :medical_issues_notes,
                                :buddy_request,
                                :notes,
                                :pickupper_1_name,
                                :pickupper_1_phone,
                                :pickupper_2_name,
                                :pickupper_2_phone,
                                :pickupper_3_name,
                                :pickupper_3_phone,
                                :highlight,
                                :can_photograph,
                                :group_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def shirt_sizes
    ["Youth Small", "Youth Medium", "Youth Large","Small", "Medium","Large","XL", "XXL"]
  end
  
  def find_age(birthdate)
    now = Time.now.utc.to_date
    now.year - birthdate.year - ((now.month > birthdate.month || (now.month == birthdate.month && now.day >= birthdate.day)) ? 0 : 1)
  end
  
  def pretty_print_date(date)
    date.strftime("%m/%d/%Y")
  end

  def find_shirt_size(size_id)
    if size_id
      return shirt_sizes[size_id]
    else
      return "N/A"
    end
  end
  
end

app/helpers/kids_helper.rb
module KidsHelper
  def grade_types
    ["Pre-K", "4k", "5k", "1st", "2nd", "3rd", "4th", "5th", "6th"]
  end

  def current_grade(last_grade_id)
    last_grade_id ||=0
    lg = last_grade_id
    if lg == 8
      return "7th"
    else
      return grade_types.at(lg + 1)
    end
  end
end

app/views/kids/_errors.html.erb
<% if @kid.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>
 
    <ul>
    <% @kid.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

app/views/kids/_kid_form.html.erb
<hr>
<h3>Child Info</h3>
<hr>
<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Name</label>
  <div class="col-sm-4">
    <%= f.text_field :first_name, class: "form-control" %>
    <small class="form-text text-muted">First Name</small>
  </div>
  <div class="col-sm-4">
    <%= f.text_field :last_name, class: "form-control" %>
    <small class="form-text text-muted">Last Name</small>
  </div>
</div>

<div class="form-group row">
  <!-- <label class="col-sm-2 text-sm-right col-form-label">Gender</label> -->
  <div class="col-sm-8 offset-md-3">
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, :male, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Male</span>
    </label>
    <label class="custom-control custom-radio">
      <%= f.radio_button :gender, :female, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Female</span>
    </label>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 text-sm-right col-form-label">Birthday</label>
  <div class="col-sm-8">
    <%= f.date_select :birthdate, { :start_year => 2004, :end_year => 2017, :prompt => { day: 'Day', month: 'Month', year: 'Year' }, :use_short_month => true, :order => [:day, :month, :year]}, class: "custom-select" %>
  </div>
</div>

<div class="form-group row">
  <label class="col-md-3 text-sm-right col-form-label">Last Grade Completed</label>
  <div class="col-sm-8">
    <%= f.select :last_grade_id, grade_types.map.with_index{ |s, i| [s, i]}, {}, {class: "custom-select"}  %>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-3 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :church_member, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Regular Attendee</span>
    </label>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Invited By</label>
  <div class="col-sm-8 ">
  <%= f.text_field :invited_by, class: "form-control" %>
  <small class="form-text text-muted">If you were invited by a member of Brushy Creek please give their name.</small>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Class Buddy</label>
  <div class="col-sm-8">
  <%= f.text_field :buddy_request, class: "form-control" %>
  <small class="form-text text-muted">If you would like your child to be in a class with a specific friend please give their name and we will make every effort to place them together.</small>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-8 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :can_photograph, checked: true, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Can be photographed</span>
    </label>
    <small class="form-text text-muted">Is your child allowed to be inclueded in photographs or videos relating to VBS.</small>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-8 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :allergies, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Allergies</span>
    </label>
  </div>
  <div class="col-sm-8 offset-md-3">
    <%= f.text_area :allergies_notes, placeholder: "Alergies, Epipen, etc.",  class: "form-control"%>
  </div>
</div>

<div class="form-group row">
  <div class="col-sm-6 offset-md-3">
    <label class="custom-control custom-checkbox">
      <%= f.check_box :medical_issues, class: "custom-control-input" %>
      <span class="custom-control-indicator"></span>
      <span class="custom-control-description">Other Medical Issues</span>
    </label>
  </div>
  <div class="col-sm-8 offset-md-3">
    <%= f.text_area :medical_issues_notes, placeholder: "",  class: "form-control"%>
  </div>
</div>

<hr>
<h3>Parent/Guardian Info</h3>
<hr>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Name</label>
  <div class="col-sm-8">
    <%= f.text_field :parent_name, class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Email</label>
  <div class="col-sm-8">
    <%= f.text_field :parent_email,type: "eamil", class: "form-control" %>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Phone Number</label>
  <div class="col-sm-8">
    <%= f.text_field :parent_phone, type: "tel", class: "form-control" %>
  </div>
</div>

<div class="form-group">
  <div class="row">
    <label class="col-sm-3 text-sm-right col-form-label">Address</label>
    <div class="col-sm-8">
      <%= f.text_field :address, class: "form-control" %>
      <small class="form-text text-muted">Street</small>
    </div>
  </div>
  <div class="row">
    <div class="col-3 offset-md-3">
      <%= f.text_field :city, class: "form-control" %>
      <small class="form-text text-muted">City</small>
    </div>
    <div class="col-2">
      <%= f.select :state, CS.states(:us),{}, class: "custom-select w-100"%>
      <small class="form-text text-muted">State</small>
    </div>
    <div class="col-3">
      <%= f.text_field :zipcode, class: "form-control" %>
      <small class="form-text text-muted">Zipcode</small>
    </div>
  </div>
</div>

<hr>
<h3>Pickup/Emergency Contacts</h3>
<p>Additonal people we can contact in an emergency. They are also authorized to sign your child out.</p>
<hr>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Contact 1</label>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_1_name, class: "form-control" %>
    <small class="from-text text-muted">Name</small>
  </div>
    <div class="col-sm-4">
    <%= f.text_field :pickupper_1_phone, type: "tel", class: "form-control" %>
    <small class="from-text text-muted">Phone Number</small>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Contact 2</label>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_2_name, class: "form-control" %>
    <small class="from-text text-muted">Name</small>
  </div>
    <div class="col-sm-4">
    <%= f.text_field :pickupper_2_phone, type: "tel", class: "form-control" %>
    <small class="from-text text-muted">Phone Number</small>
  </div>
</div>

<div class="form-group row">
  <label class="col-sm-3 text-sm-right col-form-label">Contact 3</label>
  <div class="col-sm-4">
    <%= f.text_field :pickupper_3_name, class: "form-control" %>
    <small class="from-text text-muted">Name</small>
  </div>
    <div class="col-sm-4">
    <%= f.text_field :pickupper_3_phone, type: "tel", class: "form-control" %>
    <small class="from-text text-muted">Phone Number</small>
    </div>
</div>

app/views/kids/confirm.html.erb
<div class="jumbotron">
  <h1>You're Registered!</h1>
  <p>Thank you for registering for <strong>Under Construction</strong>!</p>
  <p>We can't wait for your child to join us as we learn to live life in progress!</p>
  <%= link_to "Return to form", register_path, class: "btn btn-primary" %>
</div>
      

app/views/kids/register.html.erb
<% content_for :title do %>
Register Child
<% end %>

<div class="container w-75 bg-faded rounded">
  </br>
  <h1>Register New Child</h1>
  </br>
  <%= render partial: "errors", locals: {kid: @kid} %>
  <%= form_for @kid, url: confirm_path do |f| %>
  <%= render partial: "kid_form", locals: {kid: @kid, f: f, edit: 0} %>
  <br>
  <div class="row">
    <div class="col-sm-6 offset-3">
      <%= f.submit "Register", data: {"disable-with":"Saving..."}, class: "btn btn-primary"%>
    </div>
  </div>
  <% end %>
  </br>
</div>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <%= sanitize(value) %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VbsRegistration</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/public.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>